### ISSUE TITLE
label and directory list - many duplicate entries

### ISSUE THREAD

**Issue by gsf600y** [bogenpirat/remote-torrent-adder#182] opened 2016-12-10 21:05 UTC
I'm using the "Label/Directory interactivity" option.

At some point recently, I've ended up with loads and loads and loads of duplicate entries.  I'm manually click the red "X" next to them to remove, but it's a never ending task.

I uninstalled RTA and installed it again, but all the duplicate entries are still there. (is there a way to clear them out easily?).

![rta](https://cloud.githubusercontent.com/assets/24498661/21076143/f2ee6be0-bf1b-11e6-8c04-e6b50ea4f0a1.jpg)

Thanks for the great tool!

**Comment by bogenpirat** [comment] 2016-12-10 22:03
removing and re-installing the extension completely clears the settings, so that should work.

this is however not desired behavior, so i'll take a look at it now.

**Comment by bogenpirat** [comment] 2016-12-11 02:51
alright, can't reproduce this behavior.

here's a quick way of clearing the labels: go to the extension's options page, hit f12 and enter this code, possibly also changing the variable n in case you have more than one server, counting from the left, starting at 0:

`var n = 0;
var servers = JSON.parse(localStorage.getItem("servers"));
servers[0].labellist = "[]";
localStorage.setItem("servers", JSON.stringify(servers));`

then afterwards, please document for me for what behavior exactly the contents of the label list seem to be duplicated on your end.

thanks.

**Comment by gsf600y** [comment] 2016-12-12 10:44
Ok, it's occurred again.
I cleared all the labels.

Then, I added a few torrents:
 - the first I added, I entered a new directory & label, both called "TV"
 - after doing a few more selecting that same category,
 - then I added another torrent, and entered a directory of "books".
 - And again with "Games".
I'm not 100% sure that was the order I entered them.  I don't recall seeing any duplicates in the list at this point - but I *could* have missed something.

Now having turned my PC on this morning, I added another torrent and noticed that my drop down list shows:
  Games
  TV
  Books
  TV
  Books


I'll clear the list again, and spend a while purposely trying to recreate it, and note the EXACT steps.

**Comment by realpatriot** [comment] 2016-12-12 14:25
I am seeing the same behavior and over a period of adding multiple torrents the performance of Chrome gets slower and eventually forces me to close chrome because I no longer responds.  The extension itself doesn't seem to cause a spike in mem but the memory of page that is using the extension balloons to GB's.
![image](https://cloud.githubusercontent.com/assets/4175917/21102600/116c0c82-c03c-11e6-89a6-d3f64263ff1e.png)

**Comment by bogenpirat** [comment] 2016-12-12 14:35
@gsf600y thanks a lot, i think i fixed it in bbc6ab2 which i will be pushing out in 1.2.8.3 in a few minutes (may take an hour to propagate to web store).

@realpatriot that is super curious if indeed RTA is the cause of it. from my understanding of the issue, you must've had literally hundreds of thousands of entries in that list. try disabling RTA and see if the tab still grows to that size.

either way, please post here again to let me know if the fix hasn't worked, i'm closing it until then.

**Closed by bogenpirat** 2016-12-12 14:35 UTC

**Comment by realpatriot** [comment] 2016-12-12 15:03
Thanks.  First image is the same site as before with the RTA disabled.  The remaining images are running the same tests on a different website.  You can see the webpages memory balloon.  Let me know if you need more details to repro.
![image](https://cloud.githubusercontent.com/assets/4175917/21103860/5c0f03f2-c041-11e6-81b7-99e621078234.png)

**Comment by bogenpirat** [comment] 2016-12-12 15:20
just out of curiosity, what does `document.querySelectorAll("#adddialog_label option").length` pasted into the tab's developer console (F12) say?

anyway, `var n = 0; var servers = JSON.parse(localStorage.getItem("servers")); servers[n].dirlist = "[]"; localStorage.setItem("servers", JSON.stringify(servers));` will clear that list out too.

**Comment by realpatriot** [comment] 2016-12-12 15:27
0 and then 1996612 after clicking a dl.

If I run the query in the dev console I get "VM220:1 Uncaught TypeError: Cannot read property '0' of null ..."

**Comment by bogenpirat** [comment] 2016-12-12 15:31
that's two million. and perfectly explains why your performance is going to shit.

that second line of code i wrote in the last paragraph needs to be pasted in the extension's scope. so you'll need to go to `chrome://extensions/?id=oabphaconndgibllomdcjbfdghcmenci`, click on background page and paste it there. that'll wipe them all out.
