### ISSUE TITLE
Getting error code 0

### ISSUE THREAD

**Issue by Doezer** [bogenpirat/remote-torrent-adder#200] opened 2017-04-09 11:20 UTC
It started a few days ago (this week I'd say, maybe last week), I have an error code 0 when I try to use RTA.
![error-RTA](https://cloud.githubusercontent.com/assets/11655673/24836797/d249b1b6-1d25-11e7-9653-ec9451e729b9.png)
The configuration of the extension and seedbox didn't change.
I'm using Chrome Canary, but tried under Chrome regular and same issue.
Is there a log file somewhere?

**Comment by bogenpirat** [comment] 2017-04-09 11:24
Might be a dupe of #198. Rutorrent, right? I'll probably write together a workaround release to test for both you and the guy over there. If possible, subscribe to that issue and turn on notifications so you get an email when I post there. If your issue turns out to be separate, I'll reopen here.

**Comment by Doezer** [comment] 2017-04-09 11:25
Yeah it's the same, I just turned on the errors and got this message:
https://i.imgur.com/RGruT7Q.png

**Closed by bogenpirat** 2017-04-09 11:24 UTC
