### ISSUE TITLE
Server responded with irregular HTTP error code : 403

### ISSUE THREAD

**Issue by thewonderer73** [bogenpirat/remote-torrent-adder#168] opened 2016-08-11 01:33 UTC
I was using qBitorrent 3.1.10 on raspberry pi 3 / raspbian build.  Compiled libtorrent 1.0.9 and qBittorrent 3.3.6 and now I receive the error code  Server responded with irregular HTTP error code : 403

Password / IP address all the same.

**Comment by bogenpirat** [comment] 2016-08-13 15:20
probably a duplicate of issue #145

**Closed by bogenpirat** 2016-08-13 15:20 UTC
